#!/usr/bin/env node
/* Pull the app's typefaces from Google Fonts into public/fonts/ and generate
 * styles/fonts.css, so the running app needs no CDN.
 *
 * Why self-host: this is an offline-first app used in gyms with no signal. A
 * CDN stylesheet is one more thing that has to resolve before the page looks
 * right, and a service worker can't cache cross-origin responses it can't read.
 *
 * Run once, commit the result. Re-run only to change weights or refresh files.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const OUT_FONTS = path.join(ROOT, 'public', 'fonts');
const OUT_CSS = path.join(ROOT, 'styles', 'fonts.css');

// Google serves woff2 only to browsers it recognises; anything else gets ttf.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

const FAMILIES = 'family=Barlow+Condensed:wght@500;600;700&family=Barlow:wght@400;500;600&family=JetBrains+Mono:wght@400;500';
const CSS_URL = `https://fonts.googleapis.com/css2?${FAMILIES}&display=swap`;

const slug = s => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

// Basic Latin. The app's content is English; shipping Cyrillic and Vietnamese
// subsets would multiply the byte count for glyphs nothing here renders.
const isLatin = range => range.includes('U+0000-00FF');

async function main() {
  const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();

  const blocks = css.split('@font-face').slice(1);
  const faces = [];

  for (const block of blocks) {
    const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
    const weight = block.match(/font-weight:\s*(\d+)/)?.[1];
    const style = block.match(/font-style:\s*(\w+)/)?.[1] ?? 'normal';
    const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
    const range = block.match(/unicode-range:\s*([^;]+);/)?.[1] ?? '';

    if (!family || !weight || !url) continue;
    if (!isLatin(range)) continue;
    if (faces.some(f => f.family === family && f.weight === weight)) continue;

    faces.push({ family, weight, style, url, file: `${slug(family)}-${weight}.woff2` });
  }

  if (!faces.length) throw new Error('No latin woff2 faces found — did the Google Fonts CSS format change?');

  mkdirSync(OUT_FONTS, { recursive: true });
  let total = 0;

  for (const face of faces) {
    const bytes = Buffer.from(await (await fetch(face.url)).arrayBuffer());
    writeFileSync(path.join(OUT_FONTS, face.file), bytes);
    total += bytes.length;
    console.log(`  ${face.file.padEnd(28)} ${(bytes.length / 1024).toFixed(1)} KB`);
  }

  const rules = faces.map(f => `@font-face {
  font-family: '${f.family}';
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: swap;
  src: url('../fonts/${f.file}') format('woff2');
}`).join('\n\n');

  writeFileSync(OUT_CSS, `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.
 *
 * Self-hosted so the app has no CDN dependency: a service worker cannot cache a
 * cross-origin font response it is not allowed to read, and this app has to look
 * right in a gym with no signal.
 *
 * Latin subset only. Open Font License — see public/fonts/OFL.txt.
 */

${rules}
`);

  console.log(`\n${faces.length} faces, ${(total / 1024).toFixed(0)} KB total`);
  console.log(`Wrote ${path.relative(ROOT, OUT_CSS)}`);
}

main();
